### ISSUE TITLE
Include services

### ISSUE THREAD

**Issue by cipo80** [Jannos-443/PRTG-WinServices#1]
Hello Jannos,

I'm starting to use your fantastic script PRTG-WinServices, regarding "includes", is it possible to include some services in the checks and, if isn't present/started, give an alarm? I want to be really sure to install the antivirus in all servers!
I've try, but isn't working, probably "includes" means something else, in that case is it possible to insert this kind of list?

Thank you in advance

**Comment by Jannos-443** [comment]
Hello cipo80,

you are right, includepattern is just for filtering. For example only monitor Intel Services.

Please try the latest Script with the "CriticalServicePattern" and "CriticalServiceMustRun" Parameters. I hope this helps you :)

I also added more examples.

best regards

**Comment by cipo80** [comment]
Hello Jannos, great, very thank you!

I just try the CriticalServicePattern and it's working, but isn't working the CriticalServiceMustRun, or probably I haven't understand how to use it. For sure I missing something.
For example if I use as parameter -CriticalServiceMustRun ^(CsFalconService)$' the sensor stay green als oif the service missing.
If I use -CriticalServicePattern ^(CsFalconService)$' the sensor give the error because the service missing, but the "criticalService" i nthe grid stay at 0, please check the screenshots
![2022-07-20_12h31_22](https://user-images.githubusercontent.com/13929079/179961323-ce85a28e-e69c-41d7-bc26-b57a5b9ea14d.png)

**Comment by Jannos-443** [comment]
I think it should be `-ComputerName "%host" -CriticalServicePattern '^(CsFalconService)$' -CriticalServiceMustRun`

`-CriticalServicePattern '^(CsFalconService)$'`  -> filters for "CsFalconService" Services that are **preset**. CriticalService will be the number of matching services

`-CriticalServicePattern '^(CsFalconService)$ CriticalServiceMustRun'`  -> filters for "CsFalconService" Services that are **preset and running**. CriticalService will be the number of matching services

**Comment by cipo80** [comment]
Perfect, now I understand the "logic" behind and it's working thank you again!
If you want to make "perfect", please write this explanation on comment inside the script ! : )
