### ISSUE TITLE
find channels for monitored services

### ISSUE THREAD

**Issue by JerBiz44** [Jannos-443/PRTG-WinServices#2]
Hi Jannos,

First, Thanks you verry much !
This script help me really !
I have no success to have a dedicated channed for each services monitored.
Actually i configured the sensor like this : 

-ComputerName "%host" -Username "%windowsuser" -Password "%windowspassword" -IncludePattern '^(name of service 1|name of service 2)$' -CriticalServicePattern '^(name of service 1|name of service 2)$' -CriticalServiceLimit 2

Is it possible to add an option to create the channels for each services monitored ?
And also an option to not view this channel : Automatic Services not running ?

The idea is to have only the view on the critical services states (sum and details).

Thanks you very much.

I learned a lot in powershell and the prtg monitoring with you !

**Comment by Jannos-443** [comment]
Hi Jerbiz44,

I added a "HideAutomaticNotRunning" and "ChannelPerService" Parameter. (see the new screenshot)
Hope this helps you.

thank you for the great feedback :)

**Comment by JerBiz44** [comment]
Thanks you very much. It's working like a charm ! and we have less parameters than before ! Too strong !
